# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.132.0/containers/debian/.devcontainer/base.Dockerfile
ARG VERSION="10.5.3.2"
ARG APAMA_BUILDER=store/softwareag/apama-builder:${VERSION}

# Use the build environment
FROM ${APAMA_BUILDER} 
USER sagadmin:sagadmin





# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

